export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"


export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"


export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_REQUEST"



export const CLEAR_ERROR = "CLEAR_ERROR"


export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL"
export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL"
export const OPEN_REGISTER_MODAL = "OPEN_REGISTER_MODAL"
export const CLOSE_REGISTER_MODAL = "CLOSE_REGISTER_MODAL"
export const OPEN_UPLOAD_FILE_MODAL = "OPEN_UPLOAD_FILE_MODAL"
export const CLOSE_UPLOAD_FILE_MODAL = "CLOSE_UPLOAD_FILE_MODAL"


export const PLAYER_SONG_REQUEST="PLAYER_SONG_REQUEST"
export const PLAYER_SONG_SUCCESS="PLAYER_SONG_SUCCESS"


export const GET_ALL_SONGS="GET_ALL_SONGS"



export const OPEN_MOBILE_TOGGLE="OPEN_MOBILE_TOGGLE"
export const CLOSE_MOBILE_TOGGLE="CLOSE_MOBILE_TOGGLE"