import PulseLoader from '@/components/PulseLoader'
import SearchInput from '@/components/SearchInput'
import SongCard from '@/components/SongCard'
import { getAuthSession } from '@/lib/auth'
import { File } from '@/lib/models/file'
import { User } from '@/lib/models/user'
import { Metadata } from 'next'
import React, { Suspense } from 'react'

export const metadata: Metadata = {
    title: 'Search your fav',
    description: 'Generated by SG',
}


const page = async ({ searchParams }: { searchParams: any }) => {
    const session = await getAuthSession()

    // if (!session?.user) {
    //     return (
    //         <div>

    //         </div>
    //     )
    // }

    const { name } = searchParams
    const keyward = name?.slice("%20") || " "
    const k = keyward.split(" ")
    const reg = new RegExp(k.join("|"), "i")
    const songs = await File.find({
        $or: [
            { title: { $regex: reg } },
            { author: { $regex: reg } },
        ]
    })
    // @ts-ignore
    const user = await User.findById(session?.user?._id).populate({ path: "liked" })



    return (
        <div className='p-5 pb-5 w-full'>
            <SearchInput />
            <Suspense fallback={<PulseLoader />}>
                {
                    songs.length === 0 &&
                    <div className=' mt-10 w-full flex justify-center'>
                        No match found
                    </div>
                }
                <Suspense fallback={<PulseLoader />}>
                    <div className='grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-7 w-full gap-5 bg-neutral-900 rounded-xl pt-5'>
                        {
                            songs && songs.map((song) => {
                                if (user) {
                                    const isliked = user.liked.find((item: any) => item._id.toString() === song._id.toString());
                                    return <SongCard key={song._id} song={song} isLiked={!!isliked} userId={user._id} />
                                }
                                return <SongCard key={song._id} song={song} />
                            })
                        }
                    </div>
                </Suspense>
            </Suspense>
        </div >
    )
}

export default page